from tkinter import *
import database as d
import settings as s

s.win.geometry("500x1000")
s.win.title("Student Manager")

space = Label(s.win)
space.pack()
l1 = Label(s.win,text = "STUDENT MANAGER")
l1.pack()
space = Label(s.win)
space.pack()
l2 = Label(s.win,text = "Name")
l2.pack()
NameEntry = Entry(s.win,bg="white",fg="grey",font=("Arial",20))
NameEntry.pack()
l3 = Label(s.win,text = "Age")
l3.pack()
AgeEntry = Entry(s.win,bg="white",fg="grey",font=("Arial",20))
AgeEntry.pack()
l4 = Label(s.win,text = "Course")
l4.pack()
CourseEntry = Entry(s.win,bg="white",fg="grey",font=("Arial",20))
CourseEntry.pack()
b1 = Button(s.win,text="Add Student", command=lambda: d.add_student(NameEntry.get(),AgeEntry.get(),CourseEntry.get()))
b1.pack()
space = Label(s.win)
space.pack()
s.InputSpace = Label(s.win)
s.InputSpace.pack()
space = Label(s.win)
space.pack()
l5 = Label(s.win,text = "STUDENTS")
l5.pack()
space = Label(s.win)
space.pack()
s.InputSpace2 = Label(s.win)
s.InputSpace2.pack()
InputSpace = Label(s.win)
space = Label(s.win)
space.pack()
b2 = Button(s.win,text="Refresh Record",command=d.display_students)
b2.pack()
space = Label(s.win)
space.pack()
l6 = Label(s.win,text = "DELETE STUDENT")
l6.pack()
space = Label(s.win)
space.pack()
DeleteEntry = Entry(s.win,bg="white",fg="grey",font=("Arial",20))
DeleteEntry.pack()
b3 = Button(s.win,text="Delete",command=lambda: d.delete_student(DeleteEntry.get()))
b3.pack()
space = Label(s.win)
space.pack()
s.InputSpace3 = Label(s.win)
s.InputSpace3.pack()




s.win.mainloop()